// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6SMD8DQMekStCn3PkjDGJQArSarF1f0',
    appId: '1:660430162511:web:8edccb936953b991cb783a',
    messagingSenderId: '660430162511',
    projectId: 'tutoriel-flutter-ddd',
    authDomain: 'tutoriel-flutter-ddd.firebaseapp.com',
    storageBucket: 'tutoriel-flutter-ddd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKz_xEUQSkEPUFdwlyCUpW4cSu3CqzuiY',
    appId: '1:660430162511:android:818b4808532b587fcb783a',
    messagingSenderId: '660430162511',
    projectId: 'tutoriel-flutter-ddd',
    storageBucket: 'tutoriel-flutter-ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoq1jsUuiiE8heprnt3a8QGz6yhjP3NnU',
    appId: '1:660430162511:ios:10787ae4176b2576cb783a',
    messagingSenderId: '660430162511',
    projectId: 'tutoriel-flutter-ddd',
    storageBucket: 'tutoriel-flutter-ddd.appspot.com',
    iosClientId: '660430162511-ktb8c2qctqc6udcjqh7p8pq0sl2kcv7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddd',
  );
}
